package com.example.subly.data.repository;

import com.example.subly.data.local.UserLocalDataSource;
import com.example.subly.data.local.UserEntity;
import com.example.subly.data.model.RegistrationRequestModel;
import com.example.subly.data.model.RegistrationResponseModel;
import com.example.subly.data.remote.UserRemoteDataSource;
import java.time.LocalDate;

/**
 * Concrete implementation of UserRepository.
 * Orchestrates data from remote and local sources.
 */
public class RegistrationRepository implements UserRepository {
    private final UserRemoteDataSource remoteDataSource;
    private final UserLocalDataSource localDataSource;

    public RegistrationRepository(UserRemoteDataSource remoteDataSource, UserLocalDataSource localDataSource) {
        this.remoteDataSource = remoteDataSource;
        this.localDataSource = localDataSource;
    }

    @Override
    public RegistrationResponseModel registerUser(RegistrationRequestModel request) {
        // 1. Store locally first with PENDING status

        saveUserLocally(request, "PENDING", "");

        // 2. Attempt remote registration
        RegistrationResponseModel response = remoteDataSource.registerUser(request);

        // 3. If successful, update the local record with SYNCED status and the server-generated UID
        if (response != null && response.isSuccess()) {
            saveUserLocally(request, "SYNCED", response.getUserId());
        }

        return response;
    }

    private void saveUserLocally(RegistrationRequestModel request, String syncStatus, String firebaseUid) {
        // Create the entity with current registration data
        UserEntity userEntity = new UserEntity(
            request.getFirstName(),
            request.getLastName(),
            request.getEmail(),
            LocalDate.now(),
            "UNVERIFIED",
            syncStatus,
            firebaseUid,
            "FREE",
            0 // localId will be auto-generated by Room
        );

        // Call the data source to persist
        // Note: upsertUser is a suspend function. In a full implementation, 
        // this would be handled within a CoroutineScope or via Java-Kotlin interop utilities.
        try {
            localDataSource.upsertUser(userEntity, null); 
        } catch (Exception e) {
            // Log persistence error
        }
    }
}
